(function(){
'use strict';
var FEED='https://script.google.com/macros/s/AKfycbw-TllTpk_dbFjHhmojgeai9gKNGRzRaA_BtMooVSLeqvg614mONQyrpElC4M8vqP51/exec';
var VAT=1.05,OFGEM={low:1600,medium:2500,high:3800},REGIONS={10:'Eastern',11:'East Mids',12:'London',13:'Manweb',14:'Midlands',15:'Northern',16:'Norweb',17:'Scottish Hydro',18:'Scottish Power',19:'Seeboard',20:'Southern',21:'Swalec',22:'Sweb',23:'Yorkshire'};
var state={tier:2,region:11,eff:3.2,icon:'🚙',period:'month',usageMode:'medium',stress:0,data:null,status:'loading',e7NightPct:15,openDetails:{}};
var $=function(id){return document.getElementById(id)};
function number(v){if(v===null||v===undefined||v==='')return null;var x=parseFloat(String(v).replace(/[^0-9.\-]/g,''));return isNaN(x)?null:x}
function input(id){var x=parseFloat($(id).value);return isNaN(x)?0:x}
function lower(v){return String(v||'').trim().toLowerCase()}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function money(a){if(!isFinite(a))return'£—';return'£'+Math.round(state.period==='month'?a/12:a).toLocaleString('en-GB')}
function kwh(v){return Math.round(v).toLocaleString('en-GB')+' kWh'}
function homeKwh(){return input('houseKwh')||OFGEM.medium}
function tierFromName(name,type){var s=lower(name);if(type==='fixed'){if(s.indexOf('fixed saver')>=0)return 2;if(s.indexOf('fixed start')>=0)return 0;if(/^fixed\s+\d+/.test(s)||s==='fixed')return 1}if(type==='variable'){if(s.indexOf('double gold')>=0)return 2;if(/(^|\s)gold(\s|$)/.test(s))return 1;if(/(^|\s)value(\s|$)/.test(s))return 0}if(type==='variable_ev'){if(s.indexOf('double gold')>=0)return 2;if(/(^|\s)gold(\s|$)/.test(s))return 1;if(/(^|\s)value(\s|$)/.test(s))return 0}return null}
function regionRows(){var a=state.data&&Array.isArray(state.data.tariffLive)?state.data.tariffLive:[];return a.filter(function(r){var rg=parseInt(r.region_no!=null?r.region_no:r.regionNo,10),pm=lower(r.payment_method!=null?r.payment_method:r.paymentMethod);return rg===state.region&&(!pm||pm==='dd'||pm==='direct debit')})}
function mapped(){var out={0:{},1:{},2:{}};regionRows().forEach(function(r){var type=lower(r.tariff_type!=null?r.tariff_type:r.tariffType),name=r.tariff_name!=null?r.tariff_name:r.tariffName,t=tierFromName(name,type);if(t===null)return;if(type==='fixed')out[t].fixed=r;else if(type==='variable')out[t].variable=r;else if(type==='variable_ev')out[t].ev=r});return out}
function rate(row,kind){if(!row)return null;var sc,day,night;if(kind==='fixed'||kind==='variable'){sc=number(row.EDSC_Std);day=number(row.EUR_Std);night=null}else if(kind==='fixedE7'||kind==='variableE7'){sc=number(row.EDSC_E7);day=number(row.EUR_E7_Day);night=number(row.EUR_E7_Night)}else{sc=number(row.EDSC_Std);day=number(row.EUR_EV_Peak);night=number(row.EUR_EV_OffPeak)}if(sc===null||day===null||((kind==='ev'||kind.indexOf('E7')>=0)&&night===null))return null;return{sc:sc,day:day,night:night,discount:number(row.dual_fuel_discount_ex_vat)||0,name:String(row.tariff_name||''),series:String(row.fixed_series||''),fixedEnd:String(row.fixed_end_date||row.contract_end_date||''),sourceRef:String(row.source_ref||'')}}
function assumptions(){var eff=input('effOverride')||state.eff,miles=input('miles'),known=input('knownEvKwh'),total=known>0?known:(eff>0?miles/eff:0),away=clamp(input('awayPct'),0,100),home=homeKwh();var day=input('e7DayKwh'),night=input('e7NightKwh'),sum=day+night;if(sum<=0){night=home*state.e7NightPct/100;day=home-night;sum=home}return{home:home,evHome:total*(1-away/100),evAway:total*away/100,evPct:clamp(input('evNightPct'),0,100),e7Day:day,e7Night:night,e7Total:sum,dual:$('dualFuel').checked}}
function calc(r,kind,i){if(!r)return null;var day=r.day*VAT,night=r.night===null?null:r.night*VAT,sc=r.sc*VAT*365/100;if(i.dual&&r.discount)sc-=r.discount*VAT;sc=Math.max(0,sc);var hd=i.home,hn=0,carRate=day,desc='Single-rate tariff';if(kind==='ev'){hn=i.home*i.evPct/100;hd=i.home-hn;carRate=night;desc='EV: '+i.evPct+'% of normal home use in the EV cheap window'}else if(kind==='fixedE7'||kind==='variableE7'){hd=i.e7Day;hn=i.e7Night;carRate=night;desc='Economy 7: '+kwh(hd)+' day / '+kwh(hn)+' night'}var home=(hd*day+hn*(night===null?day:night))/100+sc,car=i.evHome*carRate/100;return{home:home,car:car,total:home+car,day:day,night:night,desc:desc,fixedEnd:r.fixedEnd,sourceRef:r.sourceRef,name:r.name}}
function pack(m,t,k){if(k==='fixed')return rate(m[t].fixed,'fixed');if(k==='variable')return rate(m[t].variable,'variable');if(k==='ev')return rate(m[t].ev,'ev');if(k==='fixedE7')return rate(m[t].fixed,'fixedE7');if(k==='variableE7')return rate(m[t].variable,'variableE7');return null}
function series(m){var r=m[state.tier].fixed;if(r&&r.fixed_series)return String(r.fixed_series).replace(/\D/g,'');for(var t=0;t<3;t++){r=m[t].fixed;if(r&&r.fixed_series)return String(r.fixed_series).replace(/\D/g,'')}return'—'}
function displayName(r,k,t){if(r&&r.name)return(k==='fixedE7'||k==='variableE7')?r.name+' E7':r.name;if(k==='fixed')return t===0?'Fixed Start':t===1?'Fixed':'Fixed Saver';if(k==='variable')return t===0?'Value':t===1?'Gold':'Double Gold';if(k==='ev')return'EV '+(t===0?'Value':t===1?'Gold':'Double Gold');return k==='fixedE7'?'Fixed E7':'Variable E7'}
function isVariableKind(k){return k==='ev'||k==='variable'||k==='variableE7'}
function buildBaseMatrix(m,i){var kinds=['ev','variable','variableE7','fixed','fixedE7'],out={};kinds.forEach(function(k){out[k]=[];for(var t=0;t<3;t++)out[k][t]=calc(pack(m,t,k),k,i)});return out}
function scenarioCalc(base,k){if(!base||!state.stress||!isVariableKind(k))return base;var f=1+state.stress/100;return{home:base.home*f,car:base.car*f,total:base.total*f,day:base.day,night:base.night,desc:base.desc,fixedEnd:base.fixedEnd,sourceRef:base.sourceRef,name:base.name,stress:state.stress}}
function syncE7FromPercent(){var total=homeKwh(),pct=clamp(state.e7NightPct,0,70),night=total*pct/100,day=total-night;$('e7DayKwh').value=Math.round(day);$('e7NightKwh').value=Math.round(night);$('e7NightSlider').value=Math.round(pct);$('e7SplitLabel').textContent=Math.round(pct)+'% night'}
function setUsageCustomFromE7(){var day=input('e7DayKwh'),night=input('e7NightKwh'),sum=day+night;if(sum<=0)return;state.usageMode='custom';$('houseKwh').value=Math.round(sum);$('customWrap').classList.add('show');$('usageNote').textContent=Math.round(sum).toLocaleString('en-GB')+' kWh/year';document.querySelectorAll('#usagePills button').forEach(function(b){b.classList.toggle('on',b.dataset.use==='custom')});state.e7NightPct=sum?night/sum*100:15;$('e7NightSlider').value=Math.round(state.e7NightPct);$('e7SplitLabel').textContent=Math.round(state.e7NightPct)+'% night'}
function detailHtml(m,matrix,k,t){var base=matrix[k][t],c=scenarioCalc(base,k),r=pack(m,t,k);if(!c)return'';var type=(k==='fixed'||k==='fixedE7')?'FIXED':'VARIABLE';var note=c.desc+' · Day '+c.day.toFixed(2)+'p';if(c.night!==null)note+=' · Night '+c.night.toFixed(2)+'p';if(c.fixedEnd)note+=' · fixed to '+c.fixedEnd;if(state.stress&&isVariableKind(k))note+=' · illustrative +'+state.stress+'% applied to today\'s calculated costs; live rates shown here are unchanged';if(c.sourceRef)note+=' · '+c.sourceRef;return '<div class="detail"><div class="detail-head"><strong>'+displayName(r,k,t)+' · '+(t+1)+' UW service'+(t?'s':'')+'</strong><span>'+type+'</span></div><div class="detail-grid"><div><div class="k">🏠 Home</div><div class="v">'+money(c.home)+'</div></div><div><div class="k">'+state.icon+' Car</div><div class="v">'+money(c.car)+'</div></div><div><div class="k">⚡ Total</div><div class="v">'+money(c.total)+'</div></div></div><div class="detail-note">'+note+'</div></div>'}
function renderTable(m,matrix){var groups=[{label:'Variable tariffs',cls:'',rows:[['ev','EV tariff'],['variable','Standard'],['variableE7','Economy 7']]},{label:'Fixed tariffs',cls:'fixed',rows:[['fixed','Standard'],['fixedE7','Economy 7']]}],all=[],html='';groups.forEach(function(g){html+='<tr class="group '+g.cls+'"><td colspan="4">'+g.label+'</td></tr>';g.rows.forEach(function(d){var k=d[0];html+='<tr data-row="'+k+'"><td class="tariff-name">'+d[1]+'<small>'+((k==='ev'||k==='variable'||k==='variableE7')?'variable':'fixed')+'</small></td>';for(var t=0;t<3;t++){var c=scenarioCalc(matrix[k][t],k);if(c){all.push({k:k,t:t,c:c});var open=state.openDetails[k]===t;html+='<td class="cell '+(t===state.tier?'sel ':'')+(open?'open ':'')+'" data-kind="'+k+'" data-tier="'+t+'">'+money(c.total)+'</td>'}else html+='<td class="na '+(t===state.tier?'sel ':'')+'">—</td>'}html+='</tr>';if(state.openDetails[k]!==undefined&&state.openDetails[k]!==null){var ot=state.openDetails[k];html+='<tr class="detail-row"><td colspan="4">'+detailHtml(m,matrix,k,ot)+'</td></tr>'}})});$('comparison').innerHTML=html;if(all.length){var min=Math.min.apply(null,all.map(function(x){return x.c.total}));document.querySelectorAll('#comparison td.cell').forEach(function(td){var k=td.dataset.kind,t=parseInt(td.dataset.tier,10),c=scenarioCalc(matrix[k][t],k);if(c&&Math.abs(c.total-min)<.5){td.classList.add('best');td.setAttribute('data-best-label',state.stress?'LOWEST IN SCENARIO':'LOWEST TODAY')}td.onclick=function(){if(state.openDetails[k]===t)delete state.openDetails[k];else state.openDetails[k]=t;render()}})}}
function render(){var m=mapped(),i=assumptions(),matrix=buildBaseMatrix(m,i),t=state.tier,ec=matrix.ev[t],er=pack(m,t,'ev');$('heroCarIcon').textContent=$('heroTotalIcon').textContent=state.icon;$('fixedSeries').textContent=series(m);$('heroTitle').textContent='Selected EV tariff · '+(t+1)+' UW service'+(t?'s':'');$('heroTariff').textContent=displayName(er,'ev',t);$('heroCar').textContent=ec?money(ec.car):'£—';$('heroHome').textContent=ec?money(ec.home):'£—';$('heroTotal').textContent=ec?money(ec.total):'£—';$('carMeta').textContent='🔌 '+kwh(i.evHome)+' charging';$('homeMeta').textContent='🏠 '+kwh(i.home)+' home';$('totalMeta').textContent='⚡ '+kwh(i.home+i.evHome)+' total';$('milesDisplay').textContent=Math.round(input('miles')).toLocaleString('en-GB')+' miles';for(var x=0;x<3;x++){document.querySelector('#serviceButtons button[data-tier="'+x+'"]').classList.toggle('on',x===t);$('th'+x).classList.toggle('sel',x===t)}$('stressNote').textContent=state.stress?'Illustrative +'+state.stress+'% scenario applied to today\'s calculated Variable, EV and Variable E7 electricity costs. Fixed tariffs and the hero remain on today\'s live rates.':'Directional only. The uplift is applied to today\'s calculated variable electricity costs - it is not an Ofgem forecast or a prediction of how unit rates and standing charges will move.';renderTable(m,matrix);status(m);if(!state.stress&&ec&&matrix.ev[t]&&Math.abs(ec.total-matrix.ev[t].total)>.001)console.warn('Hero/table EV mismatch detected')}
function status(m){$('feedDot').className='dot '+(state.status==='live'?'live':state.status==='error'?'warn':'');var ev=m[state.tier].ev,from=ev&&ev.valid_from?new Date(ev.valid_from):null,q='';if(from&&!isNaN(from.getTime()))q=['Jan-Mar','Apr-Jun','Jul-Sep','Oct-Dec'][Math.floor(from.getMonth()/3)]+' '+from.getFullYear();$('rateStrip').textContent=(q?'EV rates: '+q:'Live tariffs')+' · Region '+state.region+' '+REGIONS[state.region]+' · Direct Debit · VAT incl.';var count=0;for(var t=0;t<3;t++)count+=(m[t].fixed?1:0)+(m[t].variable?1:0)+(m[t].ev?1:0);$('feedNote').textContent=state.status==='live'?'Live Google Sheet feed reached · '+count+' of 9 tariff rows recognised for Region '+state.region+' · Fixed '+series(m)+' loaded.':state.status==='error'?'Live tariff feed could not be reached. No fixed or variable figures are being guessed.':'Loading the Google Sheet tariff feed…'}
function finishLoading(ok){$('loadingTitle').textContent=ok?'Live tariff data loaded':'Live tariff data unavailable';$('loadingCopy').textContent=ok?'Calculations are ready.':'The tool has opened without guessing missing live rates.';setTimeout(function(){$('loadingModal').classList.add('hide');setTimeout(function(){$('loadingModal').style.display='none'},220)},ok?180:700)}
function load(){fetch(FEED,{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(function(d){state.data=d;state.status='live';render();finishLoading(true)}).catch(function(){state.status='error';render();finishLoading(false)})}
document.querySelectorAll('#vehiclePills .vpill').forEach(function(b){b.onclick=function(){document.querySelectorAll('#vehiclePills .vpill').forEach(function(x){x.classList.remove('on')});b.classList.add('on');state.eff=parseFloat(b.dataset.eff);state.icon=b.dataset.icon;render()}});
$('miles').oninput=render;
document.querySelectorAll('#periodToggle button').forEach(function(b){b.onclick=function(){state.period=b.dataset.period;document.querySelectorAll('#periodToggle button').forEach(function(x){x.classList.toggle('on',x===b)});render()}});
document.querySelectorAll('#usagePills button').forEach(function(b){b.onclick=function(){var u=b.dataset.use;state.usageMode=u;document.querySelectorAll('#usagePills button').forEach(function(x){x.classList.toggle('on',x===b)});if(u==='custom'){$('customWrap').classList.add('show');$('usageNote').textContent=Math.round(homeKwh()).toLocaleString('en-GB')+' kWh/year';$('houseKwh').focus()}else{$('customWrap').classList.remove('show');$('houseKwh').value=OFGEM[u];$('usageNote').textContent=OFGEM[u].toLocaleString('en-GB')+' kWh/year'}syncE7FromPercent();render()}});
$('houseKwh').oninput=function(){state.usageMode='custom';syncE7FromPercent();$('usageNote').textContent=Math.round(homeKwh()).toLocaleString('en-GB')+' kWh/year';render()};
$('e7NightSlider').oninput=function(){state.e7NightPct=clamp(parseFloat(this.value)||0,0,70);syncE7FromPercent();render()};
$('e7DayKwh').oninput=function(){setUsageCustomFromE7();render()};
$('e7NightKwh').oninput=function(){setUsageCustomFromE7();render()};
document.querySelectorAll('#serviceButtons button').forEach(function(b){b.onclick=function(){state.tier=parseInt(b.dataset.tier,10);render()}});
document.querySelectorAll('#stressButtons button').forEach(function(b){b.onclick=function(){state.stress=parseInt(b.dataset.stress,10)||0;document.querySelectorAll('#stressButtons button').forEach(function(x){x.classList.toggle('on',x===b)});render()}});
$('region').onchange=function(){state.region=parseInt(this.value,10);render()};
['evNightPct','awayPct','awayRate','effOverride','knownEvKwh'].forEach(function(id){$(id).oninput=render});$('dualFuel').onchange=render;
syncE7FromPercent();render();load();
})();
