'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const intro=read('ev-shared-intro-v2.55.27.js'),contact=read('ev-customer-contact-v2.55.27.js');
const sharing=read('ev-sharing-v2.55.27.js'),cloud=read('ev-share-view-v2.55.27.js'),fixed=read('ev-fixed-compare-polish-v2.55.27.js');
const loader=read('ev/index.html'),main=read('index.html'),sw=read('sw.js');
for(const s of [intro,contact,sharing,cloud,fixed,sw,read('release-v2.55.27.js')])new vm.Script(s);
for(const p of ['ev-sharing-v2.55.27.js','ev-shared-intro-v2.55.27.js','ev-share-view-v2.55.27.js','ev-customer-contact-v2.55.27.js','ev-fixed-compare-polish-v2.55.27.js'])assert.ok(loader.includes(p),p);
assert.match(main,/release-v2\.55\.27\.js/);
assert.match(sw,/consolidated-v2-55-27-sharebridge1/);
assert.match(intro,/data\.meter\?'existing':'considering'/);
assert.match(intro,/setText\('\.personal-splash-icon','🚗'\)/);
assert.match(intro,/Your personalised UW\\nEV summary/);
assert.match(intro,/We're looking at:/);
const s=intro.indexOf('1 qualifying UW service'),r=intro.indexOf("Best EV rate - UW's variable EV tariff"),v=intro.indexOf('5% VAT included');
assert.ok(s>0&&r>s&&v>r);
assert.match(intro,/count===2\?/);
assert.match(contact,/shared-view:not\(\.shared-started\).*#acEvProfile\{display:none!important\}/);
assert.match(contact,/Go to my UW basket/);
assert.match(contact,/🚗 Your personalised UW EV summary/);
assert.match(contact,/Back to EV summary/);
assert.match(contact,/Switch VAT off to see estimated costs for the first 6 months/);
assert.match(contact,/uw-ev-interest-ticked-v1\.svg/);
assert.match(contact,/I've already ticked the EV interest box/);
assert.match(fixed,/Why not look at fixing your peak and off-peak rates with UW's Economy 7 tariff/);
assert.match(fixed,/2 extra off-peak hours/);
assert.match(fixed,/peak rates are typically higher than UW's EV peak rates/);
assert.match(cloud,/Your personalised UW\\nEV summary/);
assert.match(sharing,/Your personalised UW\\nEV summary/);
assert.match(contact,/var basketAnnual=std\.total\/vatFactor\+\(dual\?discountAnnual:0\)/);
assert.match(contact,/var evAnnual=ev\.total\/vatFactor/);
for(const h of ['1. COMPANION','2. UW QUOTE','3. EV TARIFF'])assert.ok(contact.includes(h));
console.log('EV v2.55.27 shared welcome and basket bridge regression checks passed');
